### ISSUE TITLE
Files: stuck on opening a folder

### ISSUE THREAD

**Issue by python273** [ipfs/ipfs-webui#1743] opened 2021-03-31 05:31 UTC
It gets stuck on loading screen when I click on a folder. Clicking on "files" or "pins" doesn't get it unstuck

macOS
ipfs-desktop: 0.14.0
go-ipfs: 0.8.0
UI: v2.11.4 (69cd414)

`QmRoBbkZCPKp7wK36uA3u5xBsBjzJnvGetioGn2pRxwBG3`
<img width="777" alt="Screenshot 2021-03-31 at 08 16 25" src="https://user-images.githubusercontent.com/3097956/113093893-71610500-91f9-11eb-826a-1395c61d2594.png">
stuck on this screen:
<img width="773" alt="Screenshot 2021-03-31 at 08 16 34" src="https://user-images.githubusercontent.com/3097956/113093899-732ac880-91f9-11eb-919f-a6f7d53d6c81.png">

--

network tab from dev tools:
pending request is not resolving
<img width="1085" alt="Screenshot 2021-04-13 at 05 42 53" src="https://user-images.githubusercontent.com/3097956/114489057-242e5b80-9c1b-11eb-95a1-b9bfa2d18477.png">

**Comment by lidel** [comment] 2021-05-28 13:50
This is a duplicate of https://github.com/ipfs/ipfs-webui/issues/1794, let's track this there.

**Closed by lidel** 2021-05-28 13:50 UTC
Labels: need/triage
