### ISSUE TITLE
need a better message for show why error

### ISSUE THREAD

**Issue by bluelovers** [ipfs/ipfs-webui#1830] opened 2021-07-30 14:10 UTC
**Describe the bug**

**To Reproduce**
1. upload a file whit exists same name

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/167966/127665465-c476a6ad-30be-421b-bf94-0c12164fb078.png)

![image](https://user-images.githubusercontent.com/167966/127665475-9acc1d2f-2d26-4615-9680-a68edffbff1d.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lidel** [comment] 2021-09-24 13:19
Indeed, uploading file for the second time fails without clear explanation why:
> ![2021-09-24_15-16](https://user-images.githubusercontent.com/157609/134680856-77599ed9-dd53-4c03-9230-2d9687cd4ffb.png)

We could 
1. detect that imported file already exists (check the destination path) 
2. abort operation 
3. display yellow warning message on the bottom instead of populating file import drawer with error one

**Comment by SgtPooki** [comment] 2022-12-02 21:49
duplicate of https://github.com/ipfs/ipfs-webui/issues/1612

**Closed** 2022-12-02 21:50 UTC
Labels: help wanted, exp/novice, P3, good first issue, kind/enhancement
