### ISSUE TITLE
Add a "working on it" animation when pinning a folder which is lazy-copied

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/ipfs-webui#1824] opened 2021-06-25 13:32 UTC
**Is your feature request related to a problem? Please describe.**
I'm sure that's not a super common use-case, but I lazy-mounted a folder to the MFS of my node under Windows. It's like 2 GB in size.

This can be easily done when browsing to an ipfs folder in the browser and select *import to ipfs* in the browser plugin. The Desktop App shows an import folder with the imported (or lazy mounted) ipfs item.

At this point, I'm not sure if the IPFS-Desktop client will be asked to pin/download it completely, but my guess is no. So it stays there as a lazy-mounted folder - which might break user expectations.

Anyway, if you now click on the lazy mounted folder right and select *pin* and then local node, it will be pinned locally, but this will take a while - depending on the download speed and size.

But there's zero indication about the process.

**Describe the solution you'd like**
 Maybe we should add a progress item, like for importing files at the bottom, or at least have a rotating circle where the pinned item will appear at the end, so the user gets feedback that *something* is currently done about his request.

**Describe alternatives you've considered**
I feel like if the browser plugin calls the IPFS Desktop app for an import, the user should be asked if he wants to download the item to his node, or just "lazy mount" it and download the content on the fly - maybe stream mount is the better term here.

This won't break the user expectation which might be, that "import to local node" means download.

**Comment by lidel** [comment] 2021-07-23 13:57
Thank you for filling this. There are two topics here which we should track separately:

1. We want to track pin progress across restarts and ensure local ones are resumed if they did not finish.
   - I believe this is a duplicate of https://github.com/ipfs/ipfs-webui/issues/1752, let's continue there.
2. Improving the UX of _"Import to Files on My Node"_ feature in IPFS Companion
   - Import to MFS does not fetch any new blocks - it only protects what is already in cache from GC. Lazy-copy is a good default for websites – pages that user cares about will already be in the IPFS cache, and if one wants to preload entire things, they can pin it (total size is shown in the pinning modal, making this an informed decision). 
    - Asking user if they want to preload all the data to local node is a sensible feature request  filled https://github.com/ipfs/ipfs-webui/issues/1825 to track that

**Closed by lidel** 2021-07-23 13:57 UTC
