### ISSUE TITLE
Pin button not working reliably.

### ISSUE THREAD

**Issue by MicahZoltu** [ipfs/ipfs-webui#1684] opened 2020-11-03 14:48 UTC
**Describe the bug**
I am using IPFS Desktop which has v2.11.4 UI integrated.  When I add files by IPFS hash, they show up in my files list.  I then click the `...` on the right and choose `Pin`.  Sometimes the little pin icon shows up, sometimes it does not.

**To Reproduce**
Unknown.  I can follow the same steps multiple times and sometimes I'm able to pin, sometimes I'm not.  I generally use CIDv1 hashes if that matters, though CIDv0 are also used on occasion.  This doesn't seem to be correlated though.

**Expected behavior**
When I click "Pin" the little pin icon shows up.

**Screenshots**
![image](https://user-images.githubusercontent.com/886059/97999609-7eceba80-1e26-11eb-9fd2-662cabfd5615.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: N/A
 - Version: v2.11.4

**Additional context**

**Comment by jessicaschilling** [comment] 2020-11-03 15:14
Thanks, @MicahZoltu -- we will keep an eye out for this as well, but in the meantime if you're able to find any definitely unpinnable files that we could reproduce, that would be extremely helpful.

**Comment by MicahZoltu** [comment] 2020-11-03 15:26
You can try `bafybeiet2646ne3zlmbnsg72wd23w7mqsyxkjadv4i75f3dqgjhku726jq` (Warning: 115MB, multiple files) to see if that reproduces the issue.  It is one that I currently cannot get pinned with the UI despite trying repeatedly.  I even restarted my computer (and by extension, restarted IPFS) and it still won't pin for me.  Sometimes, restarts make it so I can pin, but not for this one it seems.

Note: I haven't tried pinning via the CLI because I don't know how to access the CLI when using IPFS desktop, so I don't know if this is purely a UI issue or may be an IPFS core issue.

**Comment by olizilla** [comment] 2020-11-04 17:08
If you are comfortable digging around, you can pop open the chromium dev tools in IPFS Desktop, by hitting 
 <kbd>cmd</kbd>+<kbd>option</kbd>+<kbd>i</kbd> 
_(on macos, other key combos here https://developers.google.com/web/tools/chrome-devtools/shortcuts)_

There you may see some errors about not finding i18n language files for your current locale which you can ignore. If you try to pin this unpinnable CID, do you see any additional errors appear in the console?

> Note: I haven't tried pinning via the CLI because I don't know how to access the CLI when using IPFS desktop, so I don't know if this is purely a UI issue or may be an IPFS core issue.

IPFS Desktop can add and `ipfs` command to your system path, if you open the app menu and select
Preferences > Command Line tools

**Comment by lidel** [comment] 2020-11-04 21:27
I believe this is an issue with content discovery, and also has some implications to the way we track pinning progress (now vs near future).
Brain dump below, let me know if I misunderstood anything :pray: 

### How to reproduce

Was able to reproduce pinning problem with ephemeral go-ipfs 0.7.0 alone (ensures we test default config and empty repo):

```console
$ docker run --rm -it --net=host ipfs/go-ipfs:v0.7.0
```

To switch CLI to use this ephemeral container, execute in other terminal:

```console
$ IPFS_PATH=$(mktemp -d)
$ echo "/ip4/127.0.0.1/tcp/5001" > $IPFS_PATH/api
```

Then, in the same terminal, try to pin mentioned CID:

```console
$ time ipfs prefs -r bafybeiet2646ne3zlmbnsg72wd23w7mqsyxkjadv4i75f3dqgjhku726jq
```

In my case it hangs after some initial success (failing to find deeper blocks).
I stopped waiting after 30 minutes, it was stuck at `Processed 406 nodes`

Due to this, I think the problem is that 
1. pinning some CIDs takes long time, and rare content may never succeed due to no providers
2. webui is unable to track "ongoing pinning" so it just shows item as "not pinned"

### UI/UX for "ongoing pinning"

The WebUI-specific problem here is that our UI does not account for the fact that pinning operation may take long time, and may not succeed at all (be stuck in limbo for days).

When it comes to remote pinning added in #1615 / https://github.com/ipfs/ipfs-gui/issues/91 things will be easy:   remote pin object is created immediately and then webui can recheck/track its status to display proper state in UI (queued|pinning|pinned|failed).

When it comes to local pins, the `ipfs pin ls` shows only "finished" pins, there is no "ongoing" state, and `ipfs pin add` is a blocking operation, so if it does not succeed fast (eg. blocks not in local datastore), will introduce confusing UX.

Normally I'd suggest we add some "background pinning" magic to webui to track "ongoing" pinning in userland, but upcoming `ipfs pin local` commands planned by @aschmahmann  will support state and asynchronous mode, which will remove the problem on tracking "ongoing pinning". 

Due to this, I believe there is no point in investing too much time in fixing the old `ipfs pin add` API in WebUI. 
We already want to remove `/pins` from UI. 

Instead, plan for leveraging `ipfs pin local add` when it lands. 

### Hiding local pinning when data is not in local store?

Just an idea for a temporary fix until we have `pin local add`: hide "local pin" option from context menus when entire DAG is not already in datastore.

I believe the check would be to do `refs` in offline mode? (is there a better way?)
When the _entire_ DAG is not in local datastore `refs -r --offline` returns an error:

```
$ ipfs refs -r --offline bafybeice66hroljqb5lmxcjwvahkxr2els7prhwaqrp6xrfcsgw2blpt6
Error: merkledag: not found
```

**Comment by aschmahmann** [comment] 2020-11-05 01:51
👍 to @lidel's comments on the UI/UX issues with when pins take a while.

> I believe the check would be to do refs in offline mode? (is there a better way?)

Not sure off hand. You could do `ipfs dag stat --offline`, but that's not too different than your suggestion.

-----

As for this pin in particular. My suspicion is that for some reason not all of the content is actually available to the network (e.g. the only provider with all the data is behind a NAT, offline, etc.).

One way to verify this is the case would be to run on the command line `ipfs dag export bafybeice66hroljqb5lmxcjwvahkxr2els7prhwaqrp6xrfcsgw2blpt6 > output.car` on the node that you think has all the data. If that doesn't work then you may not actually have all the data, and if it does then it'd be helpful if you could post it here for us to look at.

Note: If you're on Windows use CMD instead of PowerShell when running the above command since PowerShell has trouble with binary outputs.

**Comment by jessicaschilling** [comment] 2020-11-05 15:46
After almost 9 hours of letting `ipfs dag export --offline bafybeice66hroljqb5lmxcjwvahkxr2els7prhwaqrp6xrfcsgw2blpt6 > output.car` (offline, because everything was indicating I had all the data on my local) spin, I'm getting nowhere - so thinking @aschmahmann's suspicion of not all the content being available is correct.

**Comment by MicahZoltu** [comment] 2020-11-05 18:03
IIUC, it sounds like the issue is that the UI currently doesn't have a way of differentiating between "not pinned" and "in the process of fetching so it can be pinned".  This means that when I click that pin button, a process in the background starts but the pin *icon* won't show up until the pin is complete.  In this specific example, the pin will *never* complete because the data isn't available so the pin icon will never show up.

That does seem to align with my symptoms of "sometimes the pin button doesn't work, sometimes it does".  The times it does is when I already have the files locally and pinning is just a matter of flagging them as keep forever, and the times it doesn't work are when I have to fetch a bunch of data and it takes a while or may never complete.

**Comment by jessicaschilling** [comment] 2020-11-05 18:08
@MicahZoltu ... and in the case of `bafybeiet2646ne3zlmbnsg72wd23w7mqsyxkjadv4i75f3dqgjhku726jq`, you just don't have all the content. I wasn't able to grab it either. That one's an issue with the original provider not ensuring someone is hosting the full thing.

**Comment by jessicaschilling** [comment] 2020-11-30 16:08
Note: parking this until go-ipfs 0.9; we'll know more about local pinning behavior and what's needed at that point.

**Comment by lidel** [comment] 2021-05-14 13:25
This should be fixed in the latest webui, where _Pin_ operation got replaced with _Set pinning_ modal.
Remaining work around tracking pin progress is tracked in https://github.com/ipfs/ipfs-webui/issues/1752

**Closed by lidel** 2021-05-14 13:25 UTC
Labels: area/pinning, need/triage
