### ISSUE TITLE
Tracking unknown node local usage

### ISSUE THREAD

**Issue by kallisti5** [ipfs/ipfs-webui#1776] opened 2021-05-01 13:12 UTC
**Is your feature request related to a problem? Please describe.**
It's pretty common to see people in Matrix asking about "unknown usage".

* "I see 4MiB used, but nothing is pinned. What is using that?"

Here's a good example on my node...

"21 GiB of files"
![1](https://user-images.githubusercontent.com/100110/116783462-8200d700-aa54-11eb-9418-883a99ecf8a7.png)

Ok.. I click on the text saying "21 GiB of files" to figure out what they are..
![2](https://user-images.githubusercontent.com/100110/116783493-9ba21e80-aa54-11eb-95e0-d93d83161576.png)

"... nothing. Ok. I click on pins (going away in 2.12)"
![3](https://user-images.githubusercontent.com/100110/116783511-ac529480-aa54-11eb-8d7c-9d29e3d50136.png)

So, the web UI reports i'm using 21GiB, but gives zero guidance on what that 21 GiB actually is. This sets a pretty poor user reaction and spawns a lot of help questions since "IPFS is storing stuff" -> "I have no idea what it's doing"

From a user standpoint, clicking on text conveying space is used.. i'd expect to at least get some idea on what is using that space.

**Comment by lidel** [comment] 2021-05-05 19:51
This seems to be a duplicate of https://github.com/ipfs/ipfs-webui/issues/1757, which was fixed in v2.12.x:

> This should be fixed in [v2.12.0](https://github.com/ipfs/ipfs-webui/releases/tag/v2.12.0), which simplified the way header of _Files_ looks like:
> 
> Hovering on "Files" shows explainer:
> 
> > ![2021-04-19--22-47-49](https://user-images.githubusercontent.com/157609/115301345-597a0280-a161-11eb-91dd-3de7aba57038.png)
> 
> Hovering on "All blocks" shows:
> 
> > ![2021-04-19--22-47-31](https://user-images.githubusercontent.com/157609/115301366-5f6fe380-a161-11eb-9484-d2b9259f92f4.png)

@kallisti5 if you feel the above could be improved, please fill a new issue against the new UI from v2.12.x :pray:

**Closed by lidel** 2021-05-05 19:51 UTC
Labels: need/triage
