### ISSUE TITLE
Media files not played on google chrome

### ISSUE THREAD

**Issue by nlko** [ipfs/ipfs-webui#2246] opened 2024-08-24 06:26 UTC
**Describe the bug**

I'm using the latest google chrome and the media files are not playable/viewable. (same problem on brave it seems)

However, I noticed that
- Files are playable when accessible from the local gateway;
- Files are playable when accessed with the ipfs-desktop application;
- Files are playable when accessed with the webui using firefox.

**To Reproduce**
1. Open the chrome browser
2. Navigate to webui.ipfs.io
3. In the files section click on a media file (image, audio or video)
4. The file is not accessible from the webui (broken link icon is displayed for images or the play button is greyed out for audio or video files)

**Expected behavior**
Files should be playable in chrome.

**Screenshots**

For images (broken link icon):
![image](https://github.com/user-attachments/assets/30e2b5a1-ffa0-4c1e-a60b-c1a02d9183af)

For audio/videos (play button stays greyd out):
![image](https://github.com/user-attachments/assets/f08a7a69-9c5a-4d39-b4dc-c05092249a43)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser google chrome : Versión 128.0.6613.84 (Build oficial) (64 bits)
 - ipfs version 0.29.0

**Additional context**

**Comment by lidel** [comment] 2024-08-30 19:18
Thank you for reporting this.

I was able to reproduce it, but it occurs only on non-local origins like https://webui.ipfs.io because the protocol of localhost gateway gets upgraded to https for some reason:

> ![2024-08-30_21-15_1](https://github.com/user-attachments/assets/724f312d-cb8d-4688-997b-7bd40e44b4c5)

There is no TLS on localhost, and that produces error:

> ![2024-08-30_21-15](https://github.com/user-attachments/assets/9e1e5208-0a7b-458a-a40b-cec389b0d4e3)

**Comment by lidel** [comment] 2024-08-30 22:15
Confirmed this was fixed in https://github.com/ipfs/ipfs-webui/pull/2253
You can use https://deb.webui.ipfs.io/ until a new release is cut next week.

**Closed by lidel** 2024-08-30 22:15 UTC
Labels: kind/bug, exp/novice, P1, area/screen/files, effort/hours
