### ISSUE TITLE
Attempted to resolve locale that does not exist

### ISSUE THREAD

**Issue by gnh1201** [ipfs/ipfs-webui#1999] opened 2022-08-05 04:00 UTC
**Describe the bug**
The WebUI attempts to resolve a locale that does not exist. Eventually, WebUI rendering fails.

**To Reproduce**
This issue can be seen by accessing the WebUI from a non-English desktop.

**Expected behavior**
If the locale does not exist, it should be automatically resolved as `en`.

**Screenshots**
![image](https://user-images.githubusercontent.com/4439601/182998086-977ff940-cfc7-4004-b09f-6cf53f86e7b9.png)

![image](https://user-images.githubusercontent.com/4439601/182998209-0501a23c-88bf-4f32-add9-f731a9aa62d0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 103

**Additional context**

Nothing

**Comment by lidel** [comment] 2022-08-05 19:05
ipfs-webui will read locale sent by your browser, and look for the best variant available.
this search is done via http requests, and getting 404 (Not Found) for some of them is part of the process (not a bug), and if no match is found  `en` is used as the last resort fallback.

We have [ko-KR](https://github.com/ipfs/ipfs-webui/tree/main/public/locales/ko-KR) here, if you want to improve it you can join project at https://www.transifex.com/ipfs/ipfs-webui/dashboard/

closing as there is no bug here.

**Comment by gnh1201** [comment] 2022-08-06 17:53
I'm sorry, but could you take a look again? It's attempting to connect `ko/status.json`, not `ko-KR/status.json`.

There seems to be a problem with handling notation such as `**-**`.

**Comment by lidel** [comment] 2022-08-09 00:39
@gnh1201 ack, let's double-check:
- is your browser  sending requests only for `ko` and none for `ko-KR`?  (or both?)
- are you able to share "Request headers" your browser sends (namely, `Accept-Language` one)?

**Comment by gnh1201** [comment] 2022-08-09 02:07
Thank you :) Here are the `Accept-Language` header values.

* Chrome 104: en-US,en;q=0.9,ko-KR;q=0.8,ko;q=0.7
* Edge 104: ko,en;q=0.9,en-US;q=0.8

**Comment by lidel** [comment] 2022-08-09 14:23
- In Chrome, your browser should send requests for both `ko` and `ko-KR` versions. Is that not ther case?
- In Edge, is the problem that your browser does not attempt to read `ko-KR`?

(The connection error you experience is not related to locales)

**Comment by gnh1201** [comment] 2022-08-10 01:21
`ko` and `ko-KR` are the same locale. `ko` should automatically be set to `ko-KR`.

> In Chrome, your browser should send requests for both ko and ko-KR versions. Is that not ther case?
> In Edge, is the problem that your browser does not attempt to read ko-KR?

I know that this problem is because there is no translation file for `ko`. However, since ko and ko-KR are the same, `ko` should be automatically mapped to `ko-KR`.

> (The connection error you experience is not related to locales)

**Comment by SgtPooki** [comment] 2022-08-15 16:45
Thanks for your input! Seems like our todo list should be:

- [ ] reproduce this error
- [ ] no translation file for ko
- [ ] ko should be automatically mapped to ko-KR.

**Closed** 2022-08-17 20:15 UTC
Labels: exp/novice, P2, need/analysis, need/maintainer-input
