### ISSUE TITLE
WebUI shows [object Object] when viewing a CID

### ISSUE THREAD

**Issue by andrew** [ipfs/ipfs-webui#1720] opened 2021-02-04 10:03 UTC
When browsing the following cid: `bafkrgqdl3ay2mz2xwwiqrhsasioueqzmozkqmbxviewshbwlhbyph7o4iw53h24c4w4kiej5vxaec5zjl652ynxfexey3pjupnkjpi5j3wbnu` ([link](bafkrgqdl3ay2mz2xwwiqrhsasioueqzmozkqmbxviewshbwlhbyph7o4iw53h24c4w4kiej5vxaec5zjl652ynxfexey3pjupnkjpi5j3wbnu)) in webui, I get this strange view:

![Screenshot 2021-02-03 at 16 23 51](https://user-images.githubusercontent.com/1060/106876618-cb4cbf00-66cf-11eb-83de-ae3fa086e6f6.png)

Viewing the same CID in IPFS desktop get's something more helpful:

![Screenshot 2021-02-04 at 10 00 28](https://user-images.githubusercontent.com/1060/106876682-e1f31600-66cf-11eb-98b3-ccbda340b2a6.png)

The CID is a gzip file added with --raw-leaves and sha2-512 hash algo

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur
 - Browser: Firefox 85
 - webui version: 2.11.1

**Comment by lidel** [comment] 2021-02-04 12:07
I vaguely remember @rafaelramalho19 fixed this some time ago (error was due to JS API changes?),
but let's keep this open until we confirm it's not a new regression.

**Comment by lidel** [comment] 2021-05-14 14:26
I confirmed that the latest webui shows the second screen, so we can close this.
Improving content-type sniffing is tracked as part of https://github.com/ipfs/ipfs-webui/issues/1665

**Closed by lidel** 2021-05-14 14:26 UTC
Labels: need/analysis, need/triage
